project/tasks/forms.py
# project/users/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, DateField, IntegerField, \
    SelectField
from wtforms.validators import DataRequired


class AddTaskForm(FlaskForm):
    task_id = IntegerField()
    name = StringField('Task Name', validators=[DataRequired()])
    due_date = DateField(
        'Date Due (mm/dd/yyyy)',
        validators=[DataRequired()], format='%m/%d/%Y'
    )
    priority = SelectField(
        'Priority',
        validators=[DataRequired()],
        choices=[
            ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'),
            ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')
        ]
    )
    status = IntegerField('Status')

project/tasks/views.py
# project/tasks/views.py


import datetime
from functools import wraps
from flask import flash, redirect, render_template, \
    request, session, url_for, Blueprint

from .forms import AddTaskForm
from project import db
from project.models import Task


################
#### config ####
################

tasks_blueprint = Blueprint('tasks', __name__)


##########################
#### helper functions ####
##########################

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap


def open_tasks():
    return db.session.query(Task).filter_by(
        status='1').order_by(Task.due_date.asc())


def closed_tasks():
    return db.session.query(Task).filter_by(
        status='0').order_by(Task.due_date.asc())


################
#### routes ####
################

@tasks_blueprint.route('/tasks/')
@login_required
def tasks():
    return render_template(
        'tasks.html',
        form=AddTaskForm(request.form),
        open_tasks=open_tasks(),
        closed_tasks=closed_tasks(),
        username = session['name']
    )


@tasks_blueprint.route('/add/', methods=['GET', 'POST'])
@login_required
def new_task():
    error = None
    form = AddTaskForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_task = Task(
                form.name.data,
                form.due_date.data,
                form.priority.data,
                datetime.datetime.utcnow(),
                '1',
                session['user_id']
            )
            db.session.add(new_task)
            db.session.commit()
            flash('New entry was successfully posted. Thanks.')
            return redirect(url_for('tasks.tasks'))
    return render_template(
        'tasks.html',
        form=form,
        error=error,
        open_tasks=open_tasks(),
        closed_tasks=closed_tasks()
    )


@tasks_blueprint.route('/complete/<int:task_id>/')
@login_required
def complete(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.update({"status": "0"})
        db.session.commit()
        flash('The task is complete. Nice.')
        return redirect(url_for('tasks.tasks'))
    else:
        flash('You can only update tasks that belong to you.')
        return redirect(url_for('tasks.tasks'))


@tasks_blueprint.route('/delete/<int:task_id>/')
@login_required
def delete_entry(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.delete()
        db.session.commit()
        flash('The task was deleted. Why not add a new one?')
        return redirect(url_for('tasks.tasks'))
    else:
        flash('You can only delete tasks that belong to you.')
        return redirect(url_for('tasks.tasks'))

project/users/views.py
# project/users/views.py


#################
#### imports ####
#################

from functools import wraps
from flask import flash, redirect, render_template, \
    request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError

from .forms import RegisterForm, LoginForm
from project import db
from project.models import User


################
#### config ####
################

users_blueprint = Blueprint('users', __name__)


##########################
#### helper functions ####
##########################


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('users.login'))
    return wrap


################
#### routes ####
################

@users_blueprint.route('/logout/')
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('role', None)
    session.pop('name', None)
    flash('Goodbye!')
    return redirect(url_for('users.login'))


@users_blueprint.route('/', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(name=request.form['name']).first()
            if user is not None and user.password == request.form['password']:
                session['logged_in'] = True
                session['user_id'] = user.id
                session['role'] = user.role
                session['name'] = user.name
                flash('Welcome!')
                return redirect(url_for('tasks.tasks'))
            else:
                error = 'Invalid username or password.'
    return render_template('login.html', form=form, error=error)


@users_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(
                form.name.data,
                form.email.data,
                form.password.data,
            )
            try:
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering. Please login.')
                return redirect(url_for('users.login'))
            except IntegrityError:
                error = 'That username and/or email already exist.'
                return render_template('register.html', form=form, error=error)
    return render_template('register.html', form=form, error=error)

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome to FlaskTaskr!!!</title>
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/yeti/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">FlaskTaskr</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if not session.logged_in %}
            <li><a href="{{ url_for('users.register') }}">Signup</a></li>
            {% else %}
            <li><a href="{{ url_for('users.logout') }}">Signout</a></li>
            {% endif %}
        </ul>
        {% if session.logged_in %}
        <ul class="nav navbar-nav navbar-right">
            <li><a>Welcome, {{username}}.</a></li>
        </ul>
        {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <div class="content">

        {% for message in get_flashed_messages() %}
          <div class="alert alert-success">{{ message }}</div>
        {% endfor %}

        {% if error %}
          <div class="error"><strong>Error:</strong> {{ error }}</div>
        {% endif %}

        {% block content %}
        {% endblock %}

      </div>
      <div class="footer">
        <hr>
        <p>&copy; <a href="https://www.realpython.com">Real Python</a></p>
      </div>
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

project/templates/login.html
{% extends "_base.html" %}

{% block content %}

<h1>Welcome to FlaskTaskr.</h1>
<h3>Please sign in to access your task list</h3>

<form class="form-signin" role="form" method="post" action="/">
  {{ form.csrf_token }}
  <div class="input-group">
    {{ form.name(placeholder="user name") }}
    {% if form.name.errors %}
      <span class="error">
        {% for error in form.name.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </div>
  <div class="input-group">
    {{ form.password(placeholder="password") }}
    {% if form.password.errors %}
      <span class="error">
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </div>
  <button class="btn btn-sm btn-success" type="submit">Sign in</button>
  <br>
  <br>
  <p><em>Need an account?</em><a href="/register">Signup!!</a></p>
</form>

{% endblock %}

project/templates/register.html
{% extends "_base.html" %}
{% block content %}

<h1>Welcome to FlaskTaskr.</h1>
<h3>Please register to access the task list.</h3>
<form method="POST" action="/register/">
  {{ form.csrf_token }}
  <div class="input-group">
    {{ form.name(placeholder="name") }}
    {% if form.name.errors %}
      <span class="error">
        {% for error in form.name.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </div>
  <div class="input-group">
    {{ form.email(placeholder="email address") }}
    {% if form.email.errors %}
      <span class="error">
        {% for error in form.email.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </div>
  <div class="input-group">
    {{ form.password(placeholder="password") }}
    {% if form.password.errors %}
      <span class="error">
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </div>
  <div class="input-group">
    {{ form.confirm(placeholder="confirm password") }}
    {% if form.confirm.errors %}
      <span class="error">
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      </span>
    {% endif %}
  </div>
  <button class="btn btn-sm btn-success" type="submit">Register</button>
  <br>
  <p><em>Already registered?</em> Click <a href="/">here</a> to login.</p>
</form>

{% endblock %}

project/templates/tasks.html
{% extends "_base.html" %}
{% block content %}

<h1>Welcome to FlaskTaskr</h1>
<br>
<a href="{{ url_for('users.logout') }}">Logout</a>
<div class="add-task">
  <h3>Add a new task:</h3>
    <form action="{{ url_for('tasks.new_task') }}" method="post">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.name(placeholder="name") }}
        {% if form.name.errors %}
          <span class="error">
            {% for error in form.name.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.due_date(placeholder="due date") }}
        {% if form.due_date.errors %}
          <span class="error">
            {% for error in form.due_date.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
      </div>
      <div class="form-group">
        {{ form.priority.label }}
        {{ form.priority }}
        {% if form.priority.errors %}
          <span class="error">
            {% for error in form.priority.errors %}
              {{ error }}
            {% endfor %}
          </span>
        {% endif %}
      </div>
      <div class="form-group"><input class="btn btn-default" type="submit" value="Submit"></div>
    </form>
</div>
<div class="entries">
  <br>
  <br>
  <h2>Open tasks:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="200px"><strong>Task Name</strong></th>
          <th width="75px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="90px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in open_tasks %}
        <tr>
          <td width="200px">{{ task.name }}</td>
          <td width="75px">{{ task.due_date }}</td>
          <td width="100px">{{ task.posted_date }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="90px">{{ task.poster.name }}</td>
          <td>
            <a href="{{ url_for('tasks.delete_entry', task_id = task.task_id) }}">Delete</a>  -
            <a href="{{ url_for('tasks.complete', task_id = task.task_id) }}">Mark as Complete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>
<br>
<br>
<div class="entries">
  <h2>Closed tasks:</h2>
  <div class="datagrid">
    <table>
      <thead>
        <tr>
          <th width="200px"><strong>Task Name</strong></th>
          <th width="75px"><strong>Due Date</strong></th>
          <th width="100px"><strong>Posted Date</strong></th>
          <th width="50px"><strong>Priority</strong></th>
          <th width="90px"><strong>Posted By</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for task in closed_tasks %}
        <tr>
          <td width="200px">{{ task.name }}</td>
          <td width="75px">{{ task.due_date }}</td>
          <td width="100px">{{ task.posted_date }}</td>
          <td width="50px">{{ task.priority }}</td>
          <td width="90px">{{ task.poster.name }}</td>
          <td>
             <a href="{{ url_for('tasks.delete_entry', task_id = task.task_id) }}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock %}